# Generated by Django 3.1.2 on 2020-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('star', models.IntegerField()),
                ('duracao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('star', models.IntegerField()),
                ('temporada', models.IntegerField()),
            ],
        ),
    ]
