# Generated by Django 3.1.3 on 2020-11-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='tipo',
        ),
    ]
